language: cpp
compiler: gcc
env:
  global:
    secure: TDeE58CIszIR3Ux9C8Q6h690j34NXNhB5NuGNY6/Ks3wZWld2ddUAssA74iKf16G9q7HHhfGurOjtYHWMOMoLwFaYP+EZhiaNwUz7PSobb8qKRyGXythmn3zDrU7DYJ+Jgve+P5CTuLCj+xCXyynNlpZrmAhvjyQrRrooMe49tus+jQFcygStINZ2h2oj4H0hC5as/mfb7WazwhexNVYXtOaNQjLDKlXiC2MqTF8dmyneomRkFC87FZa498Kj78j5TZtnavxyuj5/gKUnc2DV6XWr7PwikklnHL37h8rA/HiJrRmaL18Y/3wq/Pn9VTOExaDMBs97PxNiMiq6HZph8rRl8pMkSFSPpSo7Oa4Y7721vFiD30mlAJU9qalpJDJosLZKA+5POlrLhtKXdqCUKVu+W4k7qfOuZfcoQ+dpvoCV/0QYvCYf6ilwXLmrBQr9ki9mZaNpbq8oWyoQCQYJiGobmNEQfgUqSR/u+cNoHllxHu6CU/d2BRYKlLsj89UhttfNbcGDFYnJJKtUWBrYW/L4xqPpcMzbcmC0LZGXO9E25ScwLHN6Kw7kyZpNzG/VDBXf+Q/RU2eppse09DXSMbaGCT/x4daVmKnLVVDzYLhnRxwckpsP28oFuXMV4PEirpIRY+vB1DYPgw/LbVTR2gTjtJa4g4X881fQ6d2oLY=
addons:
  coverity_scan:
    project:
      name: RandLib
      description: Build submitted via Travis CI
    notification_email: samarin_ad@mail.ru
    build_command_prepend: "./configure; make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-5
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
script:
- qmake
- make
